version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: your-accounts
    container_name: your-accounts
    working_dir: /code
    volumes:
      - .:/code
      - /code/node_modules/
      - ./:/workspace:cached
    # ports:
    #   - 5173:5173
    tty: true
