name: CI

on:
  push:
  pull_request:

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      PUBLIC_FIREBASE_OPTIONS: 'firebase config options'
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run check
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - tar-file: test-results.tar.gz
            src-tar: test-results.json
            upload-name: test-failure-${{ github.run_id }}
            if: failure()
          - tar-file: coverage.tar.gz
            src-tar: coverage
            upload-name: coverage-${{ github.run_id }}

        upload: [sub1, sub2]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
      - name: Archive test
        if: ${{matrix.if}}
        shell: bash
        run: tar -czf ${{ matrix.tar-file }} ${{ matrix.upload-name }}
      - name: Upload test results
        if: ${{matrix.if}}
        uses: actions/upload-artifact@v3
        with:
          retention-days: 3
          name: ${{ matrix.tar-file }}
          path: ${{ matrix.upload-name }}
